<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MIAPP68" failures="1" tests="1" name="Default test" time="21.779" errors="0" timestamp="2023-12-09T11:09:23 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="20.031">
    <failure type="java.lang.AssertionError" message="expected [https://www.chilternoakfurniture.co.uk/account/login?return_url=%2Faccount] but found [https://www.chilternoakfurniture.co.uk/challenge]">
      <![CDATA[java.lang.AssertionError: expected [https://www.chilternoakfurniture.co.uk/account/login?return_url=%2Faccount] but found [https://www.chilternoakfurniture.co.uk/challenge]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinitions.SignInStepDef.i_click_on_sign_in_button(SignInStepDef.java:71)
at âœ½.I click on Sign In button(file:///C:/Users/hp/eclipse-workspace/RLLproject/src/test/java/features/SignIn.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
